name: test
on: [
  push,
  pull_request
]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: Test
        run: go test -v ./...
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
